public  class Calculator2 {
   public static String printAndReturnMessage(String msg){
        string returnStr = msg + '.... OK Cool';
        return returnStr;
   }
   //method name
   //paramaters to pass
   //return type
   // public static boolean leapYearCheck(date dt){
   //  integer year = dt.year();
   //  boolean Ip = date.isLeapYear(year);
   //  return Ip;
   //}
   public static integer add(integer x, integer y){
    Integer sum = x + y;
    return sum;
   }
   public static integer add(integer x,Integer y ,integer z){  
   integer sum = x +y + z;
   return sum;
   }
}
