public  class CheckDatatypes {
    public void methodBoolean () {
        Boolean checkBoolean = true;
        system.debug(checkBoolean);

    }
    public void medhodInteger (){
        Integer varFirst = 1;
        integer varsecond = 2;
        system.debug(varFirst);
        system.debug(varsecond);
    }
    public void stringmethod(){
        string varname = 'Name';
        String var2name = 'Tugba';
        system.debug(varname);
        system.debug(var2name);
    }
}
