//Calculator2 calc = new Calculator2();
//string result = calc.printAndReturnMessage('this is a parameter');
//system.debug(result);
//date newDate = date.today();
//boolean newDateLYcheck = calc.leapYearCheck(newDate);
//system.debug('today date leap year check ' + newDateLYcheck);

integer sum1 = Calculator2.add(15,40);
system.debug('sum1= ' + sum1);

integer sum2 = Calculator2.add(22, 41, 5);
system.debug('sum2 is = ' + sum2);