string index2Candidate = ListDemo.candidatesList(2);
system.debug('index2Candidate = '+ index2Candidate);

ListDemo.randomIntegerList();

string index5Candidate = ListDemo.candidatesList(5);
system.debug('index 5 candidate = ' + index5Candidate);
string index0Candidate = ListDemo.candidatesList(0);
system.debug('index 0 candidate = ' + index0Candidate);


ListDemo.randomIntegerList();

ListDemo.allCats();

